language: python
python:
  - '3.7'
cache: pip
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE turing_db;'
  - cd src
  - mysql -u <root> -D <turing_db> -p < ./sql/database.sql

install:
  - pip install -r requirements.txt
script:
  - python manage.py test